export const techSkills = [
  "javascript",
  "typescript",
  "react",
  "redux",
  "node",
  "rest api",
  "css",
  "css3",
  "html",
  "html5",
  "mongodb",
  "firebase",
  "graphql",
  "next.js",
  "webpack",
  "babel",
  "jquery",
  "tailwind",
  "sass",
  "styled-components",
  "material-ui",
  "firebase",
  "netlify",
  "git",
  "github",
  "jira",
  "kanban",
  "ci/cd",
  "test-driven development",
  "continuous integraion",
  "continuous deployment",
  "artificial inteligence",
  "data visualization",
  "figma",
  "invision",
  "excel",
  "powerpoint",
];
